In [0]:
import numpy as np

print(np.__version__)

1.16.4


In [0]:
array = np.arange(20)
print(array)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [0]:
print("shape" , array.shape)
print("datatype" , array.dtype)
print("size" , array.size)
print("num dimension" , array.ndim)

shape (20,)
datatype int64
size 20
num dimension 1


In [0]:
array = np.arange(20).reshape(4,5)
array

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [0]:
print("shape" , array.shape)
print("datatype" , array.dtype)
print("size" , array.size)
print("num dimension" , array.ndim)

shape (4, 5)
datatype int64
size 20
num dimension 2


In [0]:
array = np.empty()
array = np.zeros(3,3)
array2 = 

In [0]:
rname = ['mike', 'dustin' ,'aniket jaiswal' , 'hritik jaiswal']
rnum = [1,2,3,4]
rsize = [213,1243,312,41]
rcommander = ['miller', 'duvy','kily','junu']

regiment = np.array([rname ,rnum, rsize , rcommander])
regiment




array([['mike', 'dustin', 'aniket jaiswal', 'hritik jaiswal'],
       ['1', '2', '3', '4'],
       ['213', '1243', '312', '41'],
       ['miller', 'duvy', 'kily', 'junu']], dtype='<U14')

In [0]:
regiment[:,0]

array(['mike', '1', '213', 'miller'], dtype='<U14')

In [0]:
regiment[0,:]

array(['213', '1243', '312', '41'], dtype='<U14')

In [0]:
regiment[2:,:2]

array([['213', '1243'],
       ['miller', 'duvy']], dtype='<U14')

In [0]:

random = np.random.rand(2,2)
print(random)

[[0.5299927  0.38237629]
 [0.98325407 0.17847711]]


In [0]:
random = np.random.randn(3,3)
random

array([[ 0.14677453,  1.26736743,  0.43175682],
       [-0.09388439,  1.69290913,  0.07984092],
       [ 2.27202275, -0.23948217, -0.201655  ]])

In [0]:
np.random.seed(10)
print(np.random.randn(3,3))



[[ 1.3315865   0.71527897 -1.54540029]
 [-0.00838385  0.62133597 -0.72008556]
 [ 0.26551159  0.10854853  0.00429143]]


***EXCERSICE***

In [0]:
empty = np.empty(8)
print(empty)

[1.78070112e-316 1.58101007e-322 2.24931554e-312 2.57161883e+184
 3.37922463e-057 3.73240680e-033 4.42828362e+175 4.21561467e+149]


In [0]:
zero = np.zeros(3)
zeros = np.zeros((3,3))
print("1d list \n", zero)
print("2d list : \n" ,zeros)

1d list 
 [0. 0. 0.]
2d list : 
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [0]:
one = np.ones(3)
ones = np.ones((3,3))
print("1d list \n", one)
print("2d list : \n" ,ones)

1d list 
 [1. 1. 1.]
2d list : 
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [0]:
eye = np.eye(2)
eyes = np.eye(3)
print("1d list \n", eye)
print("2d list : \n" ,eyes)

1d list 
 [[1. 0.]
 [0. 1.]]
2d list : 
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
